Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 57, in addClient
    categorie=int(data['categorie'])
KeyError: 'categorie'
Exception on /userByCategorie [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 115, in getClientByCategorie
    id=int(data['categorie'])
KeyError: 'categorie'
Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 60, in addClient
    hashed_password = hashlib.sha256((password).encode("ascii")).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)
Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 60, in addClient
    hashed_password = hashlib.sha256((password).encode("ascii")).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)
Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 60, in addClient
    hashed_password = hashlib.sha256((password).encode("ascii")).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)
Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 60, in addClient
    hashed_password = hashlib.sha256((password).encode("ascii")).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)
Exception on /userRegister [POST]
Traceback (most recent call last):
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_httpauth.py", line 174, in decorated
    return self.ensure_sync(f)(*args, **kwargs)
  File "/home/c2168068c/virtualenv/public_html/myjob2/3.10/lib/python3.10/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/c2168068c/public_html/myjob2/api/endpoints/clientEndpoint.py", line 60, in addClient
    hashed_password = hashlib.sha256((password).encode("ascii")).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 5: ordinal not in range(128)
